CREATE BEGIN;

DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;
USE burger_db;

CREATE USER IF NOT EXISTS 'NO'@'%' IDENTIFIED BY 'NO!';
GRANT ALL ON tracker_DB.* To 'NO'@'%';
FLUSH PRIVILEGES;

CREATE TABLE burgers  (

  id INT NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(30) NOT NULL,
  devoured BOOLEAN,
  PRIMARY KEY (id)
 
);

COMMIT;
